
createPendingInspection('LEC_CASE','602: Routine Environmental');
createPendingInspection('LEC_CASE','604: Environmental Final');
createPendingInspection('LEC_CASE','646: Mine Fencing');
createPendingInspection('LEC_CASE','647: Mine Fence Affidavit');
createPendingInspection('LEC_CASE','680: Notification/Official Letter');
createPendingInspection('LEC_CASE','699: Other');
createPendingInspection('LEC_CASE','700: Land Use');
createPendingInspection('LEC_CASE','701: Junk and Litter');
createPendingInspection('LEC_CASE','702: Zoning');
createPendingInspection('LEC_CASE','703: Setback');
createPendingInspection('LEC_CASE','704: Minimum Housing');
createPendingInspection('LEC_CASE','705: Contractor Complaint');
createPendingInspection('LEC_CASE','706: Building Without Permit');
createPendingInspection('LEC_CASE','707: Lot Mowing');
createPendingInspection('LEC_CASE','708: Drainage of Filthy Fluids');
createPendingInspection('LEC_CASE','709: Right of Way');
createPendingInspection('LEC_CASE','799: Other');

